# Kolla-Ansible inventory -- generated by Terraform. Do not edit by hand.
# Control nodes also back the network and monitoring groups (common multinode layout).

[control]
%{ for n in control_nodes ~}
${n.name} ansible_host=${n.ip} ansible_user=${ansible_user}
%{ endfor ~}

[network]
%{ for n in control_nodes ~}
${n.name} ansible_host=${n.ip} ansible_user=${ansible_user}
%{ endfor ~}

[compute]
%{ for n in compute_nodes ~}
${n.name} ansible_host=${n.ip} ansible_user=${ansible_user}
%{ endfor ~}

[monitoring]
%{ for n in control_nodes ~}
${n.name} ansible_host=${n.ip} ansible_user=${ansible_user}
%{ endfor ~}

[storage]
%{ for n in storage_nodes ~}
${n.name} ansible_host=${n.ip} ansible_user=${ansible_user}
%{ endfor ~}

# --- Kolla service group mappings (which inventory groups run which roles) ---
[deployment]
localhost ansible_connection=local

[baremetal:children]
control
network
compute
storage
monitoring

[tls-backend:children]
control

[common:children]
control
network
compute
storage
monitoring

[collectd:children]
compute

[grafana:children]
monitoring

[prometheus:children]
monitoring
